# Generated by Django 5.1.6 on 2025-02-06 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mycards',
            options={'verbose_name_plural': 'myCards'},
        ),
    ]
